---
spine00:
    hostname: 10.200.200.1
    username: myuser
    password: mypassword
    port: 12443
    platform: eos

leaf00:
    hostname: 10.200.200.1
    username: myuser
    password: mypassword
    port: 12444
    platform: eos

leaf01:
    hostname: 10.200.200.1
    username: myuser
    password: mypassword
    port: 12445
    platform: eos
