---
core:
    num_workers: 100
inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "/monit/inventory/hosts.yaml"
        group_file: "/monit/inventory/groups.yaml"
